version: '3.1'

services:

  web:
    build: .
    image: odoo:15
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo  
      - odoo-web-config:/etc/odoo
      - ./addons:/mnt/extra-addons
    secrets:
      - postgresql_password
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    restart: always

  db:
    image: postgres:13
    # user: root
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata 
    secrets:
      - postgresql_password
    restart: always

volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-web-config:

secrets:
  postgresql_password:
    file: odoo_pg_pass
